name: Helpfy Deployment

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Deploy react app to github pages
      uses: helpfy/deploy-gh-pages@v1
